### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by drzraf** [openeuropa/composer-artifacts#13]
It's quite a nice initiative and it'd be great to see it supporting GitLab CI

Some code has already been written for that purpose
https://github.com/shulard/laravel-build-artifacts
but having a composer plugin solves the problem of `composer` not executing dependencies' scripts.

Anyway support for GitLab needs something more than simply defining an URL in `composer.json`
A such, support object inside the `dist` key would be a first step to support forward-compatibility.

https://github.com/shulard/laravel-build-artifacts/pull/1 makes (optional) use of `ref` and `tag`, `stage`, `(job-)name` and the `private token` (which can be passed through environment).

Do you think there is a place for this inside `composer-artifacts`?

**Comment by drzraf** [comment]
Any news on this?
I'm bundling my own flavor of artifact-downloader in my PHP projects and having a composer plugins installed per-machine would be much more easy to deal with.

**Comment by drupol** [comment]
Hi @drzraf,

Sorry for the delay, most of the people here are using JIRA and we completely forget to take care of this.
Of course we are still interested into the possibility to have this working for multiple providers (Gitlab, etc etc).
Obviously, as we are not using Gitlab, it would be nice to have feedback (code and PRs) from people using it.

Do you have a pull request or anything where you could show us what you already did with this project ?

Thanks!

**Comment by drzraf** [comment]
It's derived from the above mentioned project and merge request.
The main topic is how to introduce the (multiple) arguments needed by GitLab into the object `openeuropa/composer-artifacts` expects.

Suggestion:
* Step 1:
  * Add a new `dist` of `type` == `gitlab+zip`
* Step 2: if `type==gitlab+zip`:
  * Look for `ref`, `tag`, `stage` and (job-)`name` keys
  * Look for `GITLAB_TOKEN` (or similar environment)
  * Look for `project` key which defines GitLab project and assume it's hosted on `https://gitlab.com`. If omitted, grab it from  `url` or fallback on top-level `composer.json` `name` or `homepage`
  * Look for `directory` (or `in`) key defining where to extract the tarball, fallback on project root.

Other points of interests/discussion:
 * an option to keep temporary tarball file (before extraction), useful for debug purpose.
 * an option to define which events trigger a download (install/update/pre-update/post-update)

**Comment by drupol** [comment]
So, the basically the idea would be to build an array such as:

```yaml
{
    "extra": {
        "artifacts": {
            "foo/bar": {
              "provider": "github",
              "dist": {
                "url": "https://github.com/{name}/releases/download/{version}/{project-name}-{version}.tar.gz",
                "type": "tar"
              }
            }
        }
    }
}
```

or

```yaml
{
    "extra": {
        "artifacts": {
            "foo/bar": {
              "provider": "namespace\to\full\class\path",
              "dist": {
                "url": "https://github.com/{name}/releases/download/{version}/{project-name}-{version}.tar.gz",
                "type": "tar"
              }
            }
        }
    }
}
```

And then, have a common abstract object for provider that provides most of the useful methods.

This way, we could have different providers that deals with their own logic in their own specific classes.

What do you think ?

**Comment by drupol** [comment]
I made a first try in a PR.

Could you please try to use your own plugin using this syntax in your composer.json ?

Your provider must implement the interface `OpenEuropa\ComposerArtifacts\Provider\AbstractProviderInterface`.
 
```yaml
{
    "extra": {
        "artifacts": {
            "foo/bar": {
              "provider": "namespace\\to\\full\\class\\path",
              "dist": {
                "url": "https://somewhere.else/{name}/releases/download/{version}/{project-name}-{version}.tar.gz",
                "type": "tar"
              }
            }
        }
    }
}
```

Let me know if this helped.

If you have a working Gitlab provider, let us know, we might include it here as well.
